- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - ros-secrets.yml
  vars:
    ansible_user: ubuntu
    ansible_pass: "{{ ros_adm_pass }}"
    ansible_sudo_pass: "{{ ros_adm_pass }}"
  tasks:
  - name: Add Jack's apt key
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: 3BC61284BD2281D34C2EDE8614259C593F1720C2
  - name: Install Jack's source
    template:
      src: "templates/jacks-repo.list.j2"
      dest: "/etc/apt/sources.list.d/jacks-repo.list"
      owner: root
      group: root
      mode: '0644'
  - name: Install ip-pusher
    apt:
      update_cache: yes
      name: "ip-pusher"
      state: present
  - name: Install ip-pusher config
    template:
        src: "templates/ip-pusher.json.j2"
        dest: "/etc/ip-pusher.json"
        owner: root
        group: root
        mode: '0644'
  - name: Enable ip-pusher
    systemd:
        name: "ip-pusher"
        enabled: yes
        daemon_reload: yes
