- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - ros-secrets.yml
  vars:
    ansible_user: ubuntu
    ansible_pass: "{{ ros_adm_pass }}"
    ansible_sudo_pass: "{{ ros_adm_pass }}"
  tasks:
    # Add a new user "ros"
    # This task is equivalent to "sudo useradd ros -mG dip,plugdev,dialout,netdev,video,audio -s /bin/bash -p '<ros_pass>'"
    - name: Create ros user
      user:
        name: ros
        password: "{{ ros_pass | password_hash('sha512') }}"
        groups: plugdev,dialout,netdev,video,audio
        shell: /bin/bash
        append: yes

    # Add a new user "ros-adm"
    # This task is equivalent to "sudo useradd ros -mG adm,dialout,cdrom,floppy,sudo,audio,dip,video,plugdev,lxd,netdev,ros -s /bin/bash -p '<ros_adm_pass>'"
    - name: Create ros-adm user
      user:
        name: ros-adm
        password: "{{ ros_adm_pass | password_hash('sha512') }}"
        groups: adm,dialout,cdrom,floppy,sudo,audio,dip,video,plugdev,lxd,netdev,ros
        shell: /bin/bash
        append: yes

    # Adds a source to the ros user's .bashrc
    # equivalent to "echo 'source /opt/ros/melodic/setup.bash' >> /home/ros/.bashrc" if logged in as ros user
    - name: Add ros bash env source to ros user
      lineinfile:
        path: /home/ros/.bashrc
        state: present
        owner: ros
        group: ros
        line: "source /opt/ros/melodic/setup.bash"
