- hosts: amr
  become: yes
  vars_files:
    - ros-secrets.yml
  vars:
    ansible_user: ros-adm
    ansible_pass: "{{ ros_adm_pass }}"
    ansible_sudo_pass: "{{ ros_adm_pass }}"
  tasks:
    - name: Remove ubuntu default user
      user:
        name: ubuntu
        state: absent
        remove: yes
